brsynth/galaxytools

rpFBA/wrap.xml

-upgrade rpfba to 5.9.2
-correct doc information
-reorder the arguments according to galaxy toolshed recommendation 
-add test section + test data : test with planemo ok

Test rpfba

---

rpFBA/README.md
rpFBA/test-data/rp_001_0001.xml
rpFBA/test-data/rp_001_0001_with_fba.xml
rpThermo/README.md
rpThermo/test-data/rp_013_0001.xml
rpThermo/test-data/rp_013_0001_with_thermo.xml
rpThermo/wrap.xml

- rpthermo:
update doc + upgrade to 5.9.2
add test section + tests data (tested with planemo) + README
- rpFBA:
add tests data + README

Test rpthermo

---

rpscore/README.md
rpscore/test-data/pathway.xml
rpscore/test-data/scored_pathway.xml
rpscore/wrap.xml

rpscore: Add test section and data tests + README

test(rpscore): add test section and data tests

---

sbml2sbol/README.md
sbml2sbol/test-data/lycopene.xml
sbml2sbol/test-data/sbol_lycopene_output.xml
sbml2sbol/wrap.xml

sbml2sbol : 
- upgrade to 0.1.12
- add test section and data tests + README

Test sbml2sbol

---

rpExtractSink/wrap.xml

- Upgrade rptools to 5.11.1
- Add stdio section to catch errors
- Update test section

Test rpextractsink

---

get_sbml_model/config/job_conf.xml
get_sbml_model/config/tool_conf.xml
get_sbml_model/wrap.xml

-update test section and test data
-add requirements
-update config files

Test get sbml model

---

inchi_to_sink/README.md
inchi_to_sink/config/job_conf.xml
inchi_to_sink/config/tool_conf.xml
inchi_to_sink/test-data/sink_to-detect_choline.csv
inchi_to_sink/wrap.xml

add **inchi to sink** wrapper : A command-line tool to convert Inchi string to CSV sink file for Retropath2.0 Input

Feat inchi to sink

---

selenzy-wrapper/test-data/uniprod_ids_out.xml
selenzy-wrapper/wrap.xml

Update selenzy wrapper + tests

Test selenzy

---

rpCompletion/test-data/rp_001_0001.xml
rpCompletion/test-data/rp_001_0006.xml
rpCompletion/test-data/rp_001_0011.xml
rpCompletion/test-data/rp_002_0001.xml
rpCompletion/test-data/rp_002_0011.xml
rpCompletion/test-data/rp_002_0021.xml
rpCompletion/test-data/rp_003_0001.xml
rpCompletion/test-data/rp_003_0131.xml
rpCompletion/test-data/rp_003_0261.xml
rpCompletion/wrap.xml

- upgrade rptools to 5.12.1
- update output tests

Test rpcompletion

---

rp2biosensor/wrap.xml

Upgrade rp2biosensor to 3.0.0 : add input sink file

feat(rp2biosensor): add input sink file and upgrade to 3.0.0

---

rp2biosensor/test-data/sink-h2o2.csv
rp2biosensor/wrap.xml

add test input file (sink)
update rp2biosensor to 3.1.0

test(rp2biosensor): add sink test file and update to 3.1.0

---

rpbasicdesign/wrap.xml

- fix warnings with planemo lint
- update galaxy profile to 21.09
- remove redundant validator with regex
- use true value for boolean parameter in test section
- add expect_num_outputs in both tests to verify that the filter is working.
- add more informations in help section. I specified **BBP-18500** for the standard Biolegio Parts.
- use sbml instead of xml for rpSBML inputs.

Iuc rpbasicdesign

---

dnabot/wrap.xml

- add help field for dnabot input parameters
- add more informations about dnabot in help section ; use label names to describe parameters
- add argument instead of name for parameters
- upgrade galaxy profile to 21.09

Test dnabot

---

rpExtractSink/wrap.xml

- update rpExtractSink according to IUC recommendations
- update rptools to 5.13.0
- add help field and more documentation in test section
- add cache_dir option to generate cache dir in a specified directory.

Iuc rpextractsink

---

selenzy-wrapper/wrap.xml

Mainly:
- upgrade selenzy to 0.3.0 
- add data-path option to download database (in tmp directory)
- change xml format to sbml format for input and output (pay attention to )
- reformat boolean parameter (simpler code)
- add more documentation for parameters and help section

Iuc selenzy

---

RRulesParser/wrap.xml

- Update rrparser to 2.5.0
- Add --rules-dir and --rules_file argument

feat(rrparser): update rrparser and add rules-dir option

---

RetroPath2-wrapper/config/job_conf.xml
RetroPath2-wrapper/wrap.xml

- change retropath2 ID to retropath2_wrapper
- add the column names as metadata : https://docs.galaxyproject.org/en/latest/dev/schema.html#unconditional-actions-and-column-names

Iuc retropath2

---

sbol_converter/sbol_converter_fastatosbol2.xml
sbol_converter/sbol_converter_fastatosbol3.xml
sbol_converter/sbol_converter_genbanktosbol3.xml
sbol_converter/sbol_converter_sbol2tofasta.xml
sbol_converter/sbol_converter_sbol2tosbol3.xml
sbol_converter/sbol_converter_sbol3tofasta.xml
sbol_converter/sbol_converter_sbol3togenbank.xml
sbol_converter/sbol_converter_sbol3tosbol2.xml

Here is a PR for a second version of sbol_converter where the wrappers are splitted.

feat(sbol_converter): add sbol converter (splitted wrappers)

---

rpCompletion/test-data/rp_001_0001.xml
rpCompletion/test-data/rp_001_0006.xml
rpCompletion/test-data/rp_001_0011.xml
rpCompletion/test-data/rp_002_0001.xml
rpCompletion/test-data/rp_002_0011.xml
rpCompletion/test-data/rp_002_0021.xml
rpCompletion/test-data/rp_003_0001.xml
rpCompletion/test-data/rp_003_0131.xml
rpCompletion/test-data/rp_003_0261.xml
rpCompletion/wrap.xml

- Update rptools and galaxy min version
- Add help to arguments
- Add min and max values for arguments
- Change default value of upper_flux_bound to 10000
- Update data tests (outputs) according to the new default value of upper_flux_bound

Iuc rpcompletion

---

RetroPath2-wrapper/wrap.xml

add new option `--kinstall` to avoid installing KNIME in tool dir.

fix(Retropath2_wrapper): fix writing in tool dir with kinstall option

---

sbml2sbol/wrap.xml

modify sbml2sbol wrapper according to IUC recommendations.

Iuc sbml2sbol

---

rpRanker/wrap.xml

Update rpranker according to IUC recommendations

Iuc rpranker

---

OptDoE/wrap.xml

- Update optdoe according to IUC recommendations

Iuc optdoe

---

rpreport/wrap.xml

- add doc
- add galaxy suffix and update rptools
- use && instead of ;
- add creator name

Iuc rpreport

---

rpExtractSink/wrap.xml

- Update rptools
- Add creator names

doc(rpExtractSink): add creator names and update rptools

---

DNAWeaver/wrap.xml

Update dnaweaver according to IUC recommendation.

Iuc dnaweaver

---

LCRGenie/config/job_conf.xml
LCRGenie/wrap.xml

Update LCRGenie according to IUC recommendations.

Iuc lcrgenie

---

get_sbml_model/get_sbml_model.xml

Several fixes:
* output format
* add `attribute` attribute
* add `creator` tag

fix(get_sbml_model): output fmt

---

rrparser/rrparser.xml

Several updates:
* update version 
* add `license` attribute
* add `creator` tag
* clean help section

feat(rrpser): update

---

tools/get_sbml_model/get_infos.py

Outputs the taxon id of the selected host

feat(get_sbml_model)

---

.github/workflows/test_workflows_skip.txt
workflows/retrosynthesis_workflow/retrosynthesis_workflow-tests.yml
workflows/retrosynthesis_workflow/retrosynthesis_workflow.ga

workflows `retrosynthesis`

---

workflows/straindesign_workflow/straindesign_workflow-tests.yml
workflows/straindesign_workflow/straindesign_workflow.ga

Workflows: `straindesign`

---

workflows/genetic_assembly_workflow/genetic_assembly_workflow.ga

Workflows: add `genetic assembly`

---

.github/workflows/testtools.yml
tools/selenzy_wrapper/selenzy_wrapper.xml

Tools: `selenzy_wrapper`

---

tools/rptools/macros.xml
tools/rptools/rpfba.xml

For `rpfba`:
- replace argument `--ignore_orphan_species` by `--with_orphan_species`

Update `rptools` 6.5.0

---

tools/dnabot/dnabot.xml

Hello! This is an automated update of the following tool: **dnabot**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated dnabot from version 3.1.0 to 4.1.0.
**Project home page:** https://github.com/brsynth/DNA-BOT/releases
For any comments, queries or criticism about the bot, not related to the tool being updated in this PR, please create an issue [here](https://github.com/brsynth/synbiocad-galaxy-wrappers/issues/new).

Updating dnabot from version 3.1.0 to 4.1.0

---

tools/retropath2/retropath2_wrapper.xml

Add workflow #163 
Use regex to raise `warning` and `fatal` errors

retropath2_wrapper 

---

tools/rp2paths/rp2paths.xml

`rp2paths` output extension

---

tools/retrorules/query.py
tools/retrorules/retrorules.xml

Raises: `cannot find "min_diameter"`

Fix `retrorules` tool
